### ISSUE TITLE
Release 0.1.0 broken module.json

### ISSUE THREAD

**Issue by Lunar-Dawn** [BernhardPosselt/pf2e-qftff-tools#1]
The removed comma in 4be1f7b results in invalid json and breaks the ability to update to 0.1.0 unfortunately

**Comment by BernhardPosselt** [comment]
whoops, thanks for bringing it up

**Comment by BernhardPosselt** [comment]
Can you check if the 0.1.1 release fixed it? Unfortunately wasn't able to dog food since I'm still running an old game (QftFF) on my server and waiting for more bugfixes.

**Comment by Lunar-Dawn** [comment]
44a338e1df346325ece31de6e54524373beff7d1 seems to have stripped a comma again, it looks like you have some misbehaving automated tool

**Comment by BernhardPosselt** [comment]
You're exactly right, https://github.com/BernhardPosselt/pf2e-qftff-tools/blob/master/release.sh#L22

Don't know why it didn't explode prior to that.

**Comment by BernhardPosselt** [comment]
The dangers of using sed over a json parser/writer ;)

Can you check again?

**Comment by Lunar-Dawn** [comment]
The installation worked now, updating didn't but that might have been some caching issue on my instance. My group isn't really close to where we'd need to use the module so I can't test more than that right now, unfortunately.

**Comment by BernhardPosselt** [comment]
Glad to hear. Let me know if you find issues, bugs during game sessions are no joke ;)

**Comment by BernhardPosselt** [comment]
Closing this issue for now; upgraded myself and seems to work fine.
